name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

permissions:
  contents: read

jobs:
  ci:
    strategy:
          fail-fast: false
          matrix:
            python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
            poetry-version: ["1.2.2"]
            os: [ubuntu-latest]
        runs-on: ${{ matrix.os }}
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-python@v4
            with:
              python-version: ${{ matrix.python-version }}
          - name: Run image
            uses: abatilo/actions-poetry@v2
            with:
              poetry-version: ${{ matrix.poetry-version }}
          - name: Install dependencies
            run: poetry install --no-interaction
          - name: Run pytest
            run: poetry run python pytest
          - name: Run lint
            run: poetry run flake8 core/ tests/
          - name: Run formatter
            run: poetry run black --diff --check
